CREATE TABLE STUDENT
(
STUDENT_ID 	SMALLINT ,
STUDENT_NAME 	VARCHAR(10),
COURSE 	VARCHAR(10),
AGE	 NUMERIC(10),
FEE	MONEY,
GENDER TINYINT,
EMAIL VARCHAR(20),
PH_NO BIGINT,
 )

  select * from STUDENT
  INSERT INTO EMP VALUES 1894
